[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "auth-plugin"
version = "0.5.0"
description = "A robust Python library for JWT, OAuth2, and database authentication"
readme = "README.md"
authors = [
    {name = "Visesh Agarwal", email = "viseshagarwal@outlook.com"}
]
requires-python = ">=3.8"  # Updated for better security/features
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Security :: Cryptography",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
dependencies = [
    "PyJWT>=2.8.0",
    "pymongo>=4.6.0",
    "SQLAlchemy>=2.0.0",
    "requests>=2.31.0",
    "psycopg2-binary>=2.9.0",
    "cryptography>=41.0.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.1.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "mypy>=1.5.0"
]

[project.urls]
Homepage = "https://github.com/viseshagarwal/auth-plugin"
Documentation = "https://auth-plugin.readthedocs.io"
Repository = "https://github.com/viseshagarwal/auth-plugin.git"
Issues = "https://github.com/viseshagarwal/auth-plugin/issues"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --cov=auth_plugin"

[tool.black]
line-length = 88
target-version = ["py38"]

[tool.isort]
profile = "black"
multi_line_output = 3